### ISSUE TITLE
Upgrade Java version from 5 to 6,7 or 8?

### ISSUE THREAD

**Issue by hestad** [urbancamo/javaapiforkml#16]
At least java 6, so that we can remove the jaxb-dependencies.

Btw. is this project dead? I see 3 PRs since spring and no acitivity. Does anyone know of other active Java KML libs?

**Comment by ZiglioNZ** [comment]
There's been nobody actively developing  it for a few years now but I'm sure someone would be able to merge your pull requests, should you bother to send any

**Comment by ZiglioUK** [comment]
There's been nobody actively developing it for a few years now and someone moved the project to GitHub perhaps two years ago. Feel free to fork the project.
I can't see the need for other KML libraries, it's not that the standards evolves rapidly.
My biggest complaint is the complexity involved with jaxb, I find it really slow at warming up, perhaps due to classpath scanning.

**Comment by hestad** [comment]
I'll see how the three current PRs get handled first.

**Comment by mischah** [comment]
Sorry, this project is not actively maintained :pensive:

See #18 for further information.

**Comment by laubfall** [comment]
Actually working on it.

**Comment by urbancamo** [comment]
As of 3.x.x supports Java 11.
