### ISSUE TITLE
Support for JakartaEE 9

### ISSUE THREAD

**Issue by danshome** [urbancamo/javaapiforkml#29]
Are there plans to release support for JakartaEE 9 now that you have moved the project to Github?

**Comment by kristofdho** [comment]
I second this. This is currently keeping us from updating other dependencies as newer versions of these dependencies also require JakartaEE instead of JavaEE. I know it's possible to have both at the same time but it's definitely a hassle we don't want.

If needed to get things moving forward, I can look into contributing this myself. With some minimal guidance maybe as the jaxb landscape is a proper mess these days.

It also begs the question how you want to tackle the migration, and if you want to keep support for the JavaEE annotations alive or not.

**Comment by urbancamo** [comment]
Java 11 support has now been merged in.

**Comment by mischah** [comment]
Whoop 🎉 
I try to get you in contact with someone from @micromata/developers who can help to get this released to maven central …

**Comment by kristofdho** [comment]
@mischah What is the status of getting this released?

**Comment by JackPGreen** [comment]
> @mischah What is the status of getting this released?

If you want to use this early, before it's on Maven central, try the following in your `pom.xml`:

```
<repositories>
	<repository>
		<id>jitpack.io</id>
		<url>https://jitpack.io</url>
	</repository>
</repositories>
<dependencies>
	<dependency>
		<groupId>com.github.micromata</groupId>
		<artifactId>javaapiforkml</artifactId>
		<version>36e6333</version>
	</dependency>
</dependencies>`

This will build based on the `36e6333` (latest at time of writing) commit.
